baseURL = "/"
languageCode = "ru"
theme = "882"
title = "mansurov.me"
[[menu.main]]
identifier = "wish"
name = "wishlist"
url = "/wish/"
weight = 1
[[menu.main]]
identifier = "book"
name = "books"
url = "/books/"
weight = 2
