# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "882"
license = "MIT"
licenselink = "https://github.com/mnsrv/882/blob/master/LICENSE"
description = ""
homepage = "https://mansurov.me/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Sasha"
  homepage = "https://github.com/mnsrv"
